version: "3"

services:
  mlflow:
    image: 064592191516.dkr.ecr.us-east-1.amazonaws.com/mlflow:latest
    ports:
      - 80:5000
    environment:
      - MLFLOW_S3_ENDPOINT_URL="s3://064592191516-mlflow/artifacts"