version: "3"

services:
  mlflow:
    image: 064592191516.dkr.ecr.us-east-1.amazonaws.com/mlflow:2.9.2
    ports:
      - 80:5000
    environment:
      - MLFLOW_S3_ENDPOINT_URL="s3://064592191516-mlflow/artifacts"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
